Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,1 +1,103 @@
+name: 'test-gh-action-rl-protect-dummy'
+author: 'Maarten Boot'
+description: 'create a dummy action using python'
 
+branding:
+  icon: 'shield'
+  color: 'purple'
+
+inputs:
+  artifact-to-scan:
+    description: 'Path to the package file (artifact) you want to scan'
+    required: true
+
+  rl-proxy-server:
+    description: 'An optional proxy server to use'
+    required: false
+    default: ""
+    type: string
+  rl-proxy-port:
+    description: 'An optional proxy server port to use'
+    required: false
+    default: ""
+    type: string
+  rl-proxy-user:
+    description: 'An optional proxy server user to use'
+    required: false
+    default: ""
+    type: string
+  rl-proxy-password:
+    description: 'An optional proxy server password to use'
+    required: false
+    default: ""
+    type: string
+
+outputs:
+  description:
+    description: 'The result of the action: a string terminating in FAIL or PASS'
+    value: ${{ steps.scan.outputs.description }}
+  status:
+    description: 'The single word result of the action: success, failure or error'
+    value: ${{ steps.scan.outputs.status }}
+
+runs:
+  using: "composite"
+
+  steps:
+    - name: Install Python
+      uses: actions/setup-python@v6
+      with:
+        python-version: '3.14'
+    
+    - name: Install Dependencies
+      run: pip install -r requirements.txt
+      shell: bash
+    
+    - name: Pass Inputs to Shell
+      run: |
+          echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
+      shell: bash
+    
+    - name: Fetch the number's square
+      id: get-square
+      run: python src/get_num_square.py
+      shell: bash
+  
+    # -------------------------------------------
+    # Set the analysis status to pending
+    - name: Set the pending status
+      uses: ouzi-dev/commit-status-updater@v2.0.2
+      with:
+        addHoldComment: "true"
+
+    # -------------------------------------
+    # Update the status from pending to failure/success and set the descriptive text
+    - name: Set the analysis status
+      if: success() || failure()
+      uses: ouzi-dev/commit-status-updater@v2.0.2
+      with:
+        addHoldComment: "true"
+        description: ${{ steps.scan.outputs.description }}
+        status: ${{ steps.scan.outputs.status }}
+
+    - name: Dummy rl-protect using python
+      id: scan
+
+
+    # -------------------------------------
+    # Return the proper exit status
+    - name: Set the exit status
+      if: always()
+      shell: bash
+      run: |
+        case "${{ steps.scan.outputs.status }}" in
+        success)
+          exit 0
+          ;;
+        failure)
+          exit 1
+          ;;
+        *)
+          exit 101
+          ;;
+        esac
